@startuml
!theme plain
package "lcc" {
    package "Syntax checker" {
        [Lexer]
        [Syntactic Analyzer]
        [Lexer] -r[hidden]- [Syntactic Analyzer]
    }
    [Lexer] -d[hidden]- [Semantic analyzer]
    [Semantic analyzer] -r[hidden]- [Code generator]
}
@enduml

