@startuml
!theme plain
package "Syntactic analyzer" {
    [Lexer]
    [Syntax checker]
}
package "Semantic analyzer" {
    [Expression]
    [Type]
}
[Code generator]
"Syntactic analyzer" -[hidden]- [Code generator]
"Semantic analyzer" -[hidden]- [Code generator]
@enduml

